### ISSUE TITLE
Kombustion manifest isn't supporting YAML comments

### ISSUE THREAD

**Issue by iann0036** [KablamoOSS/kombustion#116]
**Describe the bug**
The kombustion.yaml file will not work as expected when YAML comments are present

**To Reproduce**
1. Create as per the following
```
Environments:
  dev:
    AccountIDs:
    - "123456789012"
    Parameters:
      key: value

      # some comment
      key2: value2
```
2. Attempt to use key2

**Expected behavior**
key2 is resolved

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: N/A
 - Version: 0.3.6

**Additional context**
N/A
