### ISSUE TITLE
Ref vales are not replaced

### ISSUE THREAD

**Issue by wenisman** [KablamoOSS/kombustion#118]
**Describe the bug**
Currently basic support for !Ref isnt working. Whilst trying to parse in a single parameter the compiled output will have no Resources

**To Reproduce**
1. create a basic vpc.yaml
``` yaml
AWSTemplateFormatVersion: 2010-09-09
Description: The base VPC
Parameters:
  CidrBlock:
    Description: The range of IPs for the VPC
    Type: String
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
```

2. Run Generate
``` bash
> kombustion upsert  --param CidrBlock=10.0.0.0/16 stacks/vpc.yaml
```

Current behaviour:
``` yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: The base VPC for the ECS cluster
Parameters:
  CidrBlock:
    Description: The range of IPs for the VPC
    Type: String
Resources: {}
```
**Expected behavior**
A basic cloudformation with the reference value populated should be created. 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - macOS High Sierra
 - Version 0.3.6
