### ISSUE TITLE
Existing Tag stop cloudformation generation

### ISSUE THREAD

**Issue by wenisman** [KablamoOSS/kombustion#119]
**Describe the bug**
Using a Tag with the official aws cloudformation stops the generation of the resource

**To Reproduce**
1. create a basic vpc.yaml
``` yaml
AWSTemplateFormatVersion: 2010-09-09
Description: The base VPC
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: foo
          Value: bar
```

2. Run generate or upsert
``` bash
> kombustion upsert stacks/vpc.yaml
```
**Expected behavior**
A basic cloudformtion should be created

current behaviour: 
incorrect cloudformation with no resources
``` yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: The base VPC for the ECS cluster

Resources: {}
```

**Desktop:**
 - OS: mac OS High Sierra
 - 0.3.7
