### ISSUE TITLE
VpcEndpointType of AWS::EC2::VPCEndpoint is removed after processing

### ISSUE THREAD

**Issue by neoghostz** [KablamoOSS/kombustion#121]
Any key:value pair that has a value of "Interface" will be stripped and removed from the CFN definition

```
  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${VPCStack}-VPCid"
      ServiceName: !Ref ServiceEndpoint
      VpcEndpointType: Interface
      SubnetIds:
        - Fn::ImportValue: !Sub "${VPCStack}-Subnet-PerimeterInternal1"
        - Fn::ImportValue: !Sub "${VPCStack}-Subnet-PerimeterInternal2"
        - Fn::ImportValue: !Sub "${VPCStack}-Subnet-PerimeterInternal3"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${SecurityStack}-SecGroup-${SecurityGroup}"
```

If you run through generate or upsert the key is removed from properties. 

Currently effects 0.3.7 and 0.3.8, it could effect earlier releases.
