### ISSUE TITLE
DeletionPolicy (and probably other *Policy) attributes are not added to resource

### ISSUE THREAD

**Issue by iann0036** [KablamoOSS/kombustion#130]
When passing in a template of the following format:

```
Resources:
    myResource:
        DeletionPolicy: Retain
        Type: AWS::Blah::Blah
```

DeletionPolicy does not appear in the generated output templates.
