### ISSUE TITLE
AWS::EC2::VPCEndpointService is not supported in version 0.4.5

### ISSUE THREAD

**Issue by julianbueno** [KablamoOSS/kombustion#137]
**Describe the bug**
I recently update to the last version 0.4.5

after trying to run my CF upsert I got:

✖  Error: No parser found
--
  | ☞  Resolution:
  | ├─ Name:    PrivateLinkEndpoint
  | ├─ Type:    AWS::EC2::VPCEndpointService
  | └─ Resolution:    You may need to install a plugin to parse the resource.

If you run the stack yaml in version 0.4.1 it works

**To Reproduce**
1. `wget -N -q https://github.com/KablamoOSS/kombustion/releases/download/v0.4.5/kombustion-linux-amd64.tgz && tar -zxvf kombustion-linux-amd64.tgz && ./kombustion --manifest-file params.yaml upsert cf/service.yaml --stack-name service`
2. our service.yaml contains the following CF
```
   PrivateLinkEndpoint:
        Type: "AWS::EC2::VPCEndpointService"
        Properties:
            NetworkLoadBalancerArns: 
                - !Ref LoadBalancer
            AcceptanceRequired: "false"
    
    PrivateLinkPermissions:
        Type: "AWS::EC2::VPCEndpointServicePermissions"
        Properties:
            AllowedPrincipals: 
                - !Sub "arn:aws:iam::${AccountId}:root" 
            ServiceId: !Ref PrivateLinkEndpoint

```
3. See error

**Expected behavior**
The stack is created
